<?php

/**
 * BaseRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $book_id
 * @property integer $value
 * @property Book $Book
 * 
 * @method integer getBookId()  Returns the current record's "book_id" value
 * @method integer getValue()   Returns the current record's "value" value
 * @method Book    getBook()    Returns the current record's "Book" value
 * @method Rating  setBookId()  Sets the current record's "book_id" value
 * @method Rating  setValue()   Sets the current record's "value" value
 * @method Rating  setBook()    Sets the current record's "Book" value
 * 
 * @package    minilib
 * @subpackage model
 * @author     Cristian Radulescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rating');
        $this->hasColumn('book_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}