<?php

/**
 * BaseAuthor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Book
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getBook() Returns the current record's "Book" collection
 * @method Author              setName() Sets the current record's "name" value
 * @method Author              setBook() Sets the current record's "Book" collection
 * 
 * @package    minilib
 * @subpackage model
 * @author     Cristian Radulescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuthor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('author');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Book', array(
             'local' => 'id',
             'foreign' => 'author_id'));
    }
}