<?php

/**
 * Book
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    minilib
 * @subpackage model
 * @author     Cristian Radulescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Book extends BaseBook
{
  /**
   * Calculate rating average based on numebr of votes
   *
   * @return int
   */
  public function getRatingAverage()
  {
    $ratings = $this->getRating();
    if (count($ratings) == 0)
    {
      return 0;
    }
    
    $values = 0;

    foreach ($ratings as $rating)
    {
      /* @var $rating Rating */
      $values += $rating->getValue();
    }

    return floor($values / count($ratings));
  }
}
