<?php

/**
 * PublisherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublisherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublisherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Publisher');
    }
}