Author:
  columns:
    name: { type: string(255), notnull: true }

Publisher:
  columns:
    name: { type: string(255), notnull: true }

Book:
  actAs: { Timestampable: ~ }
  columns:
    title: { type: string(255), notnull: true }
    author_id: { type: integer }
    publisher_id: { type: integer }
    isbn: { type: string(255), notnull: true }
    year: { type: integer, notnull: true }
    description: { type: string(4000) }
    image: { type: string(255) }
  relations:
    Author: { onDelete: SET NULL, local: author_id, foreign: id }
    Publisher: { onDelete: SET NULL, local: publisher_id, foreign: id }

Rating:
  columns:
    book_id: { type: integer, notnull: true}
    value: { type: integer, notnull: true}
  relations:
    Book: { onDelete: CASCADE, local: book_id, foreign: id }
